version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: taasuser
      POSTGRES_PASSWORD: taasuser
      POSTGRES_DB: taas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    ports:
      - "11211:11211"

  app:
    build: .
    container_name: tags-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: taasuser
      DB_PASSWORD: taasuser
      DB_NAME: taas
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - memcached

volumes:
  pgdata:
